import Header from "@/app/features/ui/components/menu/Header";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="min-h-screen  bg-gradient-to-br from-[#fefeff] via-[#e8f1ff] to-[#f9faff] text-gray-800 px-4 py-8">
        <Header />
        {children}
      </body>
    </html>
  );
}
